### ISSUE TITLE
How to configure CiiMS with Postgresql?

### ISSUE THREAD

**Issue by juliocesarbr** [charlesportwoodii/CiiMS#173]
Hi Charles, i want to use CiiMS, but i dont know how to jump, your process installation with MySQL. And you told that "MySQL 5.5+ (CiiMS can run on Postgres/SQLite, but you have to do a manual installation which isn't covered in this readme." I've try, but i dont know, because Yiic is deprecated for these.

**Comment by charlesportwoodii** [comment]
Optimal word is "should". It's not a supported configuration for CiiMS, and it's been a _long_ time since I've tried it out. You're on your own if you encounter any bugs or the installation doesn't work against the latest version of Postgres. If you want to give it a shot, the basic set steps would be:

1. Create the `config/main.php` file with a Postgres db config:

    ```php
    <?php return array(
        'name' => '<app_name>',
        'components' => array(
            'db' => array(
                'class' => 'CDbConnection',
                'connectionString' => '<yii2_pg_connection_string>',
                'emulatePrepare' => true,
                'username' => '<username>',
                'password' => '<password>',
                'charset' => 'utf8',
                'schemaCachingDuration' => '3600'
            ),
            'cache' => array(
                'class' => 'CFileCache',
            ),
        ),
        'params' => require('params.php')
    );
    ```

2. Run the migrations manually. They _should_ work, but it's been a _long_ time since I've run them against Postgres

    ```
    php web/index.php migrate up
    ```
    > This is most likely the step you'll get caught up on. CiiMS uses the standard yii migration tools, so if it doesn't work try editing `protected/migrations/m141001_145619_init.php`

3. Generate an random key, and place it in `config/params.php`. The parameter is poorly worded - this is more of a random salt value used to make your CiiMS installation unique. You can generate this from anywhere. (http://textmechanic.com/text-tools/randomization-tools/random-string-generator/ should help)

   ```php
   <?php return array(
       'encryptionKey' => '<128_character_random_string>'
   );
   ```

4. Manually inject a user into Postgres. The values should be as follows:

   ```
   id = 1
   email = <admin_email>
   password = <bcrypt_password_cost_13>
   username = <admin_email>
   user_role = 9
   status = 1
   created = 0
   updated = 0
   ```

    > You can generate the password from either the PHP CLI or from any other standard bcrypt implementation.

5. Navigate to the web portal and hope it works.

----

I can't reiterate enough though that CiiMS was built for MySQL, and that Postgres or SQLite aren't really supported configurations. The documentation says it should work because it uses the standard yii migrations.

**Comment by juliocesarbr** [comment]
I'll take the chance. Its true that it should work, let my try. If i find a way to contribute. i'll made a pull request.

Thanks
