### ISSUE TITLE
Installation: Doesn't delete two install.php files automatically

### ISSUE THREAD

**Issue by mitramichaeljade** [charlesportwoodii/CiiMS#174]
I installed ciims through CLI. I experienced some problem navigating through different page except home page. I needed to delete two install file located in protected\config and web\ directory

**Comment by charlesportwoodii** [comment]
Your web server would be configured to only load `web/index.php`, and static assets inside the `/web` directory. `web/install.php` should never be directly accessible. _Every_ request through CiiMS, including the installer is routed through `web/index.php`.

Assuming the former is done, the bootstrapper for the installer if CiiMS isn't installed/configured (https://github.com/charlesportwoodii/CiiMS/blob/master/web/index.php#L31). The presence of `web/install.php`, `config/install.php`, and `modules/install` is intentional to support mutli-tenant environments. If you have concerns about those files existing in single-tenant environments the standard approach is to delete them manually - the installer won't do this by default.

Pull requests are welcome against the [gh-pages](https://github.com/charlesportwoodii/CiiMS/tree/gh-pages) branch if you feel this should be more clearly documented.
