### ISSUE TITLE
Question on Migration

### ISSUE THREAD

**Issue by ghost** [charlesportwoodii/CiiMS#175]
Some foreign keys are not created during migration. For example, for table users, there is no fk for user_role but I can see in [Users model](https://github.com/charlesportwoodii/CiiMS/blob/master/protected/models/Users.php#L82) it should be referenced with user_roles table. Same with content_id attribute in events table. 

[comment ](https://github.com/charlesportwoodii/CiiMS/blob/master/protected/migrations/m141001_145619_init.php#L226) attribute in comments table were created as int which should be text

**Comment by charlesportwoodii** [comment]
Hi @mitramichaeljade,

Thanks for reporting this.

Outside of the comment attribute being an int instead of a text field are you encountering a specific issue when running CiiMS? Missing foreign keys at worst would result in performance degredation. 

Could you let me know the following?
- Version of CiiMS you are running. 
- Database name and version. 
- What command you used to run the migrations?

Thanks

**Comment by mitramichaeljade** [comment]
CiiMS 2.0.2
XAMPP 3.2.2
I manually run m141001_145619_init.php inside migration folder

**Comment by charlesportwoodii** [comment]
@mitramichaeljade,

Not sure if you saw f529305 yet or not - the issue you are seeing is corrected there.

As an aside, I would highly recommend using the provided Vagrant box. Presently that's the only development environment I can support.
